app:
  name: ads
db:
  adapter: postgresql
  host: localhost
  # user: dmitriybadichan
  # password: 123
pagination:
  page_size: 10
logger:
  path: log/app.log
  level: info
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST'] %>
  username: <%= ENV['RABBITMQ_USER'] %>
  password: <%= ENV['RABBITMQ_PASSWORD'] %>
  consumer_pool: 10
